### ISSUE TITLE
Хотим связаться

### ISSUE THREAD

**Issue by rusauth** [danilkorotkov/RTU5015_5024#1]
Здравствуйте! Видим вы работали с RTU контроллерами, можем как то связаться с Вами?

**Comment by danilkorotkov** [comment]
Добрый день. Какой вопрос?

**Comment by Domonap** [comment]
Мы разрабатываем кастомную прошивку для RTU5024 и собираемся опубликовать эту работу в Upwork, 
чтобы найти специалиста, который сможет выполнить эту работу.
Мы заметили, что у вас есть опыт работы с аналогичным проектом.
Интересно ли вам наш проект? наша электронная почта info@domonap.ru

**Comment by danilkorotkov** [comment]
в чем кастом?

> 13 сент. 2021 г., в 15:40, Gia Kvaratskheliya ***@***.***> написал(а):
> 
> опубликовать эту работу в Upwork,

**Comment by rusauth** [comment]
кастом в том смысле, что он будет лучше работать с нашим сервером.  
Устройство имеет микроконтроллер GD32F103C8T6 и модем Quectel M26. 
Как вы думаете, можно ли установить кастом  загрузчик и по?

**Comment by danilkorotkov** [comment]
Загрузчик да. Сервер да, но GPRS модем это выстрел в ногу с безобразной связью вплоть до нуля. 
Да и загрузчик нужен разве что для ОТА, а места в контроллере всего 64кб. Сама прошивка около 30кб с парсингом смс команд. Для синх с серевером место есть, для ота нет. Ну и для базы номеров надо ещё место оставить. С учётом постраничной организации памяти использование в СКУД просто приведет к деградации флэша. Это очень базовый камень для крупных задач

> 15 сент. 2021 г., в 07:43, Gia Kvaratskheliya ***@***.***> написал(а):
> 
> Quectel M26.

**Comment by danilkorotkov** [comment]
Опять же системный загрузчик никуда не девается и доступа к нему не документируется. 

> 15 сент. 2021 г., в 18:40, Данил ***@***.***> написал(а):
> 
> ﻿Загрузчик да. Сервер да, но GPRS модем это выстрел в ногу с безобразной связью вплоть до нуля. 
> Да и загрузчик нужен разве что для ОТА, а места в контроллере всего 64кб. Сама прошивка около 30кб с парсингом смс команд. Для синх с серевером место есть, для ота нет. Ну и для базы номеров надо ещё место оставить. С учётом постраничной организации памяти использование в СКУД просто приведет к деградации флэша. Это очень базовый камень для крупных задач
> 
>> 15 сент. 2021 г., в 07:43, Gia Kvaratskheliya ***@***.***> написал(а):
>> 
>> Quectel M26.

**Comment by rusauth** [comment]
Можно ли установить FreeRTOS на это устройство

**Comment by danilkorotkov** [comment]
Можно. Но я не пробовал.
